package com.github.denofevil.aurelia

import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ProjectRootModificationTracker
import com.intellij.openapi.util.IconLoader
import com.intellij.openapi.vfs.VirtualFileManager
import com.intellij.psi.search.FilenameIndex
import com.intellij.psi.search.GlobalSearchScope
import com.intellij.psi.util.CachedValueProvider
import com.intellij.psi.util.CachedValuesManager

/**
 * @author Dennis.Ushakov
 */
object Aurelia {
    val ICON = IconLoader.getIcon("/icons/aurelia-icon.svg", Aurelia::class.java)

    val INJECTABLE = arrayOf("bind", "one-way", "two-way", "one-time", "delegate", "trigger", "call")
    const val REPEAT_FOR = "repeat.for"
    const val VIRTUAL_REPEAT_FOR = "virtual-repeat.for"
    const val AURELIA_APP = "aurelia-app"

    private val AURELIA_DETECTOR_FILES = listOf(
            // Aurelia is included with with module loader (from jspm_packages when using JSPM) or module bundler (from node_modules when using Webpack)
            "aurelia-framework.js",
            // project generated by aurelia-cli
            "aurelia-bootstrapper.js",
            "aurelia-bootstrapper.d.ts",
            // project bootstrapped with script tag (contains aurelia-framework and other essential Aurelia modules)
            "aurelia-core.js"
    )

    fun present(project: Project) = CachedValuesManager.getManager(project).getCachedValue(project) {
        CachedValueProvider.Result.create(
                AURELIA_DETECTOR_FILES.any {
                    FilenameIndex.getFilesByName(project, it, GlobalSearchScope.allScope(project)).isNotEmpty()
                }, VirtualFileManager.VFS_STRUCTURE_MODIFICATIONS, ProjectRootModificationTracker.getInstance(project))
    }!!
}
