package com.github.denofevil.aurelia

import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ProjectRootModificationTracker
import com.intellij.openapi.vfs.VirtualFileManager
import com.intellij.psi.search.FilenameIndex
import com.intellij.psi.search.GlobalSearchScope
import com.intellij.psi.util.CachedValueProvider
import com.intellij.psi.util.CachedValuesManager

/**
 * @author Dennis.Ushakov
 */
object Aurelia {
    var INJECTABLE = arrayOf("bind", "one-way", "two-way", "one-time", "delegate", "trigger", "call")
    var REPEAT_FOR = "repeat.for"
    var AURELIA_APP = "aurelia-app"

    val AURELIA_DETECTOR_FILES = listOf(
            // Aurelia is included with with module loader (from jspm_packages when using JSPM) or module bundler (from node_modules when using Webpack)
            "aurelia-framework.js",
            // project generated by aurelia-cli
            "aurelia-bootstrapper.js",
            // project bootstrapped with script tag (contains aurelia-framework and other essential Aurelia modules)
            "aurelia-core.js"
    )

    fun present(project: Project) = CachedValuesManager.getManager(project).getCachedValue(project) {
        CachedValueProvider.Result.create(
                AURELIA_DETECTOR_FILES.any {
                    FilenameIndex.getFilesByName(project, it, GlobalSearchScope.allScope(project)).isNotEmpty()
                }, VirtualFileManager.VFS_STRUCTURE_MODIFICATIONS, ProjectRootModificationTracker.getInstance(project))
    }!!
}
